CREATE TABLE "fb_fe_actions_findings" (
	"campaignId" integer,
	"actionId" integer,
	"findingId" integer
);
--> statement-breakpoint
CREATE TABLE "fb_fe_actions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fb_fe_actions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaignId" integer,
	"targetRole" varchar(64) NOT NULL,
	"targetName" text NOT NULL,
	"value" text,
	"screenshotAfter" text,
	"before" json NOT NULL,
	"added" json NOT NULL,
	"removed" json NOT NULL,
	"after" json NOT NULL,
	"url" text NOT NULL,
	"kind" varchar(16),
	"buddyId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fb_fe_buddies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fb_fe_buddies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(10) NOT NULL,
	"slug" varchar(10) NOT NULL,
	"description" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "fb_fe_buddies_name_unique" UNIQUE("name"),
	CONSTRAINT "fb_fe_buddies_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "fb_fe_campaigns" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fb_fe_campaigns_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"startUrl" text NOT NULL,
	"status" varchar(10),
	"depth" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fb_fe_findings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fb_fe_findings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(120),
	"description" text,
	"moreInfoURL" text,
	CONSTRAINT "fb_fe_findings_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "fb_fe_hints" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fb_fe_hints_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"formValues" json NOT NULL
);
--> statement-breakpoint
ALTER TABLE "fb_fe_actions_findings" ADD CONSTRAINT "fb_fe_actions_findings_campaignId_fb_fe_campaigns_id_fk" FOREIGN KEY ("campaignId") REFERENCES "public"."fb_fe_campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fb_fe_actions_findings" ADD CONSTRAINT "fb_fe_actions_findings_actionId_fb_fe_actions_id_fk" FOREIGN KEY ("actionId") REFERENCES "public"."fb_fe_actions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fb_fe_actions_findings" ADD CONSTRAINT "fb_fe_actions_findings_findingId_fb_fe_findings_id_fk" FOREIGN KEY ("findingId") REFERENCES "public"."fb_fe_findings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fb_fe_actions" ADD CONSTRAINT "fb_fe_actions_campaignId_fb_fe_campaigns_id_fk" FOREIGN KEY ("campaignId") REFERENCES "public"."fb_fe_campaigns"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fb_fe_actions" ADD CONSTRAINT "fb_fe_actions_buddyId_fb_fe_buddies_id_fk" FOREIGN KEY ("buddyId") REFERENCES "public"."fb_fe_buddies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "fb_fe_buddies_slug_index" ON "fb_fe_buddies" USING btree ("slug");